### ISSUE TITLE
Record Tests

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_jgrapht#10]
Create a structured test report, send it to the customer and ask for acceptance.

**Comment by owdmn** [comment]
Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/25

**Comment by TAKeanice** [comment]
New Sprint: SPUNIKNSS15/SPUNIKNSS15_Organization#26

**Comment by TAKeanice** [comment]
First draft written by @RitaDo , will be uploaded soon

**Comment by TAKeanice** [comment]
@RitaDo are the tests updated? Please close this issue then.

**Comment by RitaDo** [comment]
tests and documentation are updated
