### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_jgrapht#11]
https://github.com/momits will perform a code review this week, but I can't directly assign
him to this task somehow...

**Comment by 285714** [comment]
The interface will change these days. So wait for the next sprint to begin with this task.

**Comment by TAKeanice** [comment]
@crxxn He needs to be added to the team @SPUNIKNSS15/vf2algorithm

**Comment by TAKeanice** [comment]
New Sprint: SPUNIKNSS15/SPUNIKNSS15_Organization#26
Please comment your findings

**Comment by TAKeanice** [comment]
@SPUNIKNSS15/morvdetfa have you done this? Please close if that´s the case.
