### ISSUE TITLE
Cases of failure

### ISSUE THREAD

**Issue by momits** [SPUNIKNSS15/SPUNIKNSS15_jgrapht#12]
The getGraphs() unit test allowed us to record many pairs of isomorphic graphs which are not recognized by the current VF2 implementation (only by the SubgraphIsomorphismTestUtils implementation).

https://github.com/SPUNIKNSS15/SPUNIKNSS15_GraphInformation/blob/implementation_inheritance/tests/data/observations/vf2_failures_2015_10_06.md

Handing this to @285714

**Comment by 285714** [comment]
It seems that .equals is the right choice. And we're doing nothing wrong with it, because it's not possible to add two equal vertices:
http://jgrapht.org/javadoc/org/jgrapht/Graph.html#addVertex(V)
