### ISSUE TITLE
Search other VF2 implementations

### ISSUE THREAD

**Issue by TAKeanice** [SPUNIKNSS15/SPUNIKNSS15_jgrapht#4]
and comment findings here @SPUNIKNSS15/vf2algorithm  :)

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/21

**Comment by RitaDo** [comment]
All VF2 implementations seem to use the same kind of code (same variables, same loops, same order of checks,...), only translated between different programming languages. Some implementations are
https://github.com/sneumann/pgchem/tree/master/src/vflib2/src (in C++)
https://github.com/fozziethebeat/S-Space/tree/master/src/main/java/edu/ucla/sspace/graph/isomorphism (in Java)
https://networkx.github.io/documentation/latest/_modules/networkx/algorithms/isomorphism/isomorphvf2.html#GraphMatcher.subgraph_is_isomorphic (in Python)
http://www.boost.org/doc/libs/1_56_0/boost/graph/vf2_sub_graph_iso.hpp (in C++)
