### ISSUE TITLE
Define VF2 Interface

### ISSUE THREAD

**Issue by TAKeanice** [SPUNIKNSS15/SPUNIKNSS15_jgrapht#5]
and post link to the interface definition file into the issue

Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/21

**Comment by owdmn** [comment]
Can we close this issue or is it still open in https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23 ?

**Comment by 285714** [comment]
I'm still working on the interface but there won't be some huge changes anymore.
