### ISSUE TITLE
Externalize debug output 

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_jgrapht#7]
https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/24

**Comment by owdmn** [comment]
New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/25

**Comment by TAKeanice** [comment]
This is finished, right @285714 ?
