### ISSUE TITLE
Comparing the implementation to the original VF algorithm, as proposed in the paper

### ISSUE THREAD

**Issue by owdmn** [SPUNIKNSS15/SPUNIKNSS15_jgrapht#8]
Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/23

**Comment by owdmn** [comment]
New sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/24

**Comment by TAKeanice** [comment]
@RitaDo, @285714 can you please comment the results here?

**Comment by owdmn** [comment]
Our implementation is more efficient than the reference implementation, as we use all optimizations proposed in the paper.
